import type { NextPage } from "next";
import Head from "next/head";
import { Box, Center } from "@chakra-ui/react";
import HeroTabs from "../components/heroTabs/heroTabs";
import NavBar from "../components/navBar/navBar";
import Hero from "../components/hero/hero";
const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Box>
        <NavBar />
      </Box>
      <Center p={"5"}>
        <Box>
          <Hero />
        </Box>
      </Center>
      <Center p={"5"}>
        <Box>
          <HeroTabs />
        </Box>
      </Center>
    </div>
  );
};

export default Home;
